name: Build and Push Image

on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: true
        description: "List of tags"
      build-args:
        type: string
        required: false
        description: "List of build-time variables"
      file:
        type: string
        required: false
      cache-to:
        type: string
        default: type=inline
        required: false
      cache-from:
        type: string
        required: false
      registry:
        type: string
        default: reg.dev.krd
        required: false

      # Trivy Options
      trivy:
        type: string
        required: false
        default: false
        description: Enable trivy image vulnerability check

      exit-code:
        type: number
        required: false
        default: 0
        description: Exit code when vulnerabilities were found

      severity:
        type: string
        required: false
        default: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
        description: severities of vulnerabilities to be displayed (comma separated)

      format:
        type: string
        required: false
        default: table
        description: How to display the results

    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build-push:
    name: Build and Push
    runs-on: [self-hosted, ubuntu-focal]
    timeout-minutes: 10
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build Docker images
        if: ${{ inputs.trivy }}
        uses: docker/build-push-action@v3
        with:
          load: true
          file: ${{ inputs.file }}
          tags: ${{ inputs.tags }}
          cache-to: ${{ inputs.cache-to }}
          cache-from: ${{ inputs.cache-from }}

      - name: Get First Tag
        if: ${{ inputs.trivy }}
        run: |
          FIRST_TAG=$(echo "${{ inputs.tags }}" | sed '1q;d')
          echo $FIRST_TAG
          echo "IMAGE_TAG=$FIRST_TAG" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.trivy }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_TAG }}
          format: ${{ inputs.format }}
          exit-code: ${{ inputs.exit-code }}
          severity: ${{ inputs.severity }}

      - name: Push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ inputs.file }}
          tags: ${{ inputs.tags }}
          cache-to: ${{ inputs.cache-to }}
          cache-from: ${{ inputs.cache-from }}
          build-args: ${{ inputs.build-args }}
