name: Build and Push Image

on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: true
        description: "List of tags"
      file:
        type: string
        required: false
      cache-to:
        type: string
        default: type=inline
        required: false
      cache-from:
        type: string
        required: false
      registry:
        type: string
        default: reg.dev.krd
        required: false
      trivy:
        type: string
        required: false

    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    steps:
      - name: Get Last Tag
        run: |
          LAST_TAG=$(echo $a | cut -d' ' -f1)
          echo "last tag is $LAST_TAG"
          echo "IMAGE_TAG=$LAST_TAG" >> $GITHUB_ENV
    outputs:
      IMAGE_TAG: ${{ env.IMAGE_TAG }}

  build-push:
    name: Build and Push
    needs: [setup]
    runs-on: [self-hosted, ubuntu-focal]
    timeout-minutes: 10
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build Docker images
        if: ${{ inputs.trivy }}
        uses: docker/build-push-action@v3
        with:
          load: true
          file: ${{ inputs.file }}
          tags: ${{ inputs.tags }}
          cache-to: ${{ inputs.cache-to }}
          cache-from: ${{ inputs.cache-from }}

      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.trivy }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.setup.outputs.IMAGE_TAG }}
          format: "table"

      - name: Push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ inputs.file }}
          tags: ${{ inputs.tags }}
          cache-to: ${{ inputs.cache-to }}
          cache-from: ${{ inputs.cache-from }}
